include:
- ./health.py
kind: ArchiveUploadSpec
name: health-py-Ei1U

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: health-d8a21afb-999f-4739-9fbb-27b216cbde84
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://health-py-Ei1U
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2025-04-19T11:01:00Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: health
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: health-d8a21afb-999f-4739-9fbb-27b216cbde84
      namespace: ""
  requestsPerPod: 1
  resources: {}
