include:
- ./healthcm.py
kind: ArchiveUploadSpec
name: healthcm-py-f1iD

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: healthcm-0dd1ab7e-a5ff-4e3c-bd48-12a150a7e0d0
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://healthcm-py-f1iD
  environment:
    name: python
    namespace: ""
  source:
    checksum: {}
status:
  buildstatus: none
  lastUpdateTimestamp: "2025-04-19T11:13:44Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: healthcm
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: bluesky-harvester-cm
    namespace: ""
  environment:
    name: python
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    packageref:
      name: healthcm-0dd1ab7e-a5ff-4e3c-bd48-12a150a7e0d0
      namespace: ""
  requestsPerPod: 1
  resources: {}
