apiVersion: fission.io/v1
kind: Function
metadata:
  name: reddit-comments-preprocess
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 2
      MinScale: 1
      SpecializationTimeout: 120
      TargetCPUPercent: 80 
    StrategyType: execution
  concurrency: 10  
  environment:
    name: python
    namespace: default
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: pre_processor.preprocess_reddit_comments
    packageref:
      name: my-package
      namespace: default
  requestsPerPod: 10  
  resources:
    limits:
      cpu: "500m"   
      memory: "64Mi"
    requests:
      cpu: "100m"    
      memory: "32Mi" 