apiVersion: fission.io/v1
kind: Function
metadata:
  name: harvest-reddit-comments
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: newdeploy  
      MaxScale: 2  
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 75  
    StrategyType: execution
  concurrency: 5 
  environment:
    name: python
    namespace: default
  functionTimeout: 120
  idletimeout: 120
  package:
    functionName: harvester.harvest_reddit_comments
    packageref:
      name: my-package
      namespace: default
  requestsPerPod: 5  
  resources:
    limits:
      cpu: "500m"   
      memory: "128Mi" 
    requests:
      cpu: "100m"  
      memory: "64Mi" 
  secrets:
    - name: reddit-client-id
      namespace: default
    - name: reddit-client-secret
      namespace: default
    - name: reddit-user-agent
      namespace: default
    - name: reddit-client-id-1
      namespace: default
    - name: reddit-client-secret-1
      namespace: default
    - name: reddit-user-agent-1
      namespace: default
    - name: reddit-refresh-token-1
      namespace: default
    - name: reddit-client-id-2
      namespace: default
    - name: reddit-client-secret-2
      namespace: default
    - name: reddit-user-agent-2
      namespace: default
    - name: reddit-refresh-token-2
      namespace: default
    - name: reddit-client-id-3
      namespace: default
    - name: reddit-client-secret-3
      namespace: default
    - name: reddit-user-agent-3
      namespace: default
    - name: reddit-refresh-token-3
      namespace: default