apiVersion: fission.io/v1
kind: TimeTrigger
metadata:
  creationTimestamp: null
  name: keyword-digger-timer
spec:
  cron: '@every 240s'
  functionref:
    functionweights: null
    name: keyword-digger
    type: name
