# redis-cr.yaml
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: redis
  namespace: redis
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v7.0.15
    imagePullPolicy: IfNotPresent
  redisExporter:
    image: quay.io/opstree/redis-exporter:v1.44.0
    imagePullPolicy: IfNotPresent
    port: 9121
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: perfretain
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
