alertmanager:
  enabled: false

server:
  persistentVolume:
    enabled: true
    size: 1Gi
    storageClass: perfretain

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: prometheus-storage
        spec:
          storageClassName: perfretain
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi

grafana:
  enabled: true  # Ensure Grafana is explicitly enabled
  persistence:
    enabled: true
    size: 1Gi
    accessModes:
      - ReadWriteOnce
    storageClassName: perfretain